package com.sipl.egstabdistribution.model

data class Data(
    val aadhar_no: String,
    val address: String,
    val created_at: String,
    val district: String,
    val email: String,
    val f_name: String,
    val id: Int,
    val imei_no: String,
    val ip_address: String,
    val is_active: Int,
    val l_name: String,
    val m_name: String,
    val number: String,
    val otp: Int,
    val password: String,
    val pincode: String,
    val remember_token: String,
    val role_id: Int,
    val state: String,
    val taluka: String,
    val updated_at: String,
    val user_agent: String,
    val user_profile: String,
    val village: String,
    val user_district: String,
    val user_village: String,
    val user_taluka: String,

    )